"""Render the contract pages from contract/semantics.json + constraints.json.

Called by tools/gen_contract.py; not a command of its own. One hand-written
source (semantics.json) produces both the human reference and the AI pages, and
every number comes from constraints.json through a {{key}} placeholder, so the
pages cannot drift from each other or from the firmware.

contract/pages/*.md are reference pages written by hand around {{key}}
placeholders (manifest, telemetry); they are rendered to docs/reference/.

Links inside semantics.json use two forms that are resolved per output page:
  (@path/from/sdk/root.md#anchor)  SDK-root link, made relative to the page
  (#anchor)                        anchor in docs/reference/api.md
"""
import os
import re

API_MD = "docs/reference/api.md"
KI_MD = "docs/reference/known-issues.md"
SKILL_API = "skill/api-contract.md"
SKILL_LIM = "skill/constraints.md"
PAGES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "contract", "pages")

HEADER = ("<!-- GENERATED by tools/gen_contract.py from contract/semantics.json and "
          "contract/constraints.json. Do not edit: change the sources, then run "
          "python tools/gen_contract.py. -->\n")

_KEY = re.compile(r"\{\{([a-z0-9_]+)\}\}")
_ROOT_LINK = re.compile(r"\]\(@([^)#\s]+)(#[^)\s]*)?\)")
_PAGE_LINK = re.compile(r"\]\((#[^)\s]+)\)")


class ContractError(Exception):
    pass


def _values(constraints):
    v = dict(constraints["limits"])
    v.update(constraints["derived"])
    return v


def _fill(text, vals):
    def sub(m):
        if m.group(1) not in vals:
            raise ContractError("semantics.json: unknown {{%s}}" % m.group(1))
        return str(vals[m.group(1)])
    return _KEY.sub(sub, text)


def _links(text, page, page_anchors_to_api=True):
    here = os.path.dirname(page)

    def root(m):
        rel = os.path.relpath(m.group(1), here).replace(os.sep, "/")
        return "](" + rel + (m.group(2) or "") + ")"
    text = _ROOT_LINK.sub(root, text)
    if page != API_MD and page_anchors_to_api:
        api = os.path.relpath(API_MD, here).replace(os.sep, "/")
        text = _PAGE_LINK.sub(lambda m: "](" + api + m.group(1) + ")", text)
    return text


def _cell(text):
    text = text.replace("\n", " ")
    return re.sub(r"(?<!\\)\|", r"\\|", text)


def _row(cells):
    return "| " + " | ".join(_cell(c) for c in cells) + " |"


def _table(head, rows):
    out = [_row(head), "| " + " | ".join(["---"] * len(head)) + " |"]
    out += [_row(r) for r in rows]
    return "\n".join(out)


def validate(sem, api):
    """semantics.json must cover api.json exactly."""
    want, have = set(), set()
    for g, v in api["globals"].items():
        if g == "print":
            want.add("print")
            continue
        want |= {g + "." + f for f in v["functions"]}
        want |= {g + ":" + m for m in v["methods"]}
        want |= {g + "." + c for c in v["constants"]}
    for g, v in sem["globals"].items():
        have |= {c["name"] for c in v["calls"]}
        have |= {c["name"] for c in v.get("constants", [])}
    errs = ["semantics.json: missing %s" % n for n in sorted(want - have)]
    errs += ["semantics.json: %s is not in api.json" % n for n in sorted(have - want)]
    hooks = {h["name"] for h in sem["hooks"]}
    errs += ["semantics.json: missing hook %s" % h for h in sorted(set(api["hooks"]) - hooks)]
    errs += ["semantics.json: hook %s is not in api.json" % h for h in sorted(hooks - set(api["hooks"]))]
    if errs:
        raise ContractError("\n".join(errs))


def _brief(text):
    """First sentence (outside code spans), for the compact AI table; `brief` overrides it."""
    tick = False
    for i, ch in enumerate(text):
        if ch == "`":
            tick = not tick
        elif ch == "." and not tick and (i + 1 == len(text) or text[i + 1] in " \n") \
                and not text[max(0, i - 3):i + 1].endswith(("e.g.", "i.e.")):
            return text[:i + 1]
    return text


def _failure(c):
    parts = [p for p in (c["bad"], c["fail"]) if p and p != "—"]
    return "; ".join(parts) or "—"


def _hooks_full(sem):
    rows = [[f"`{h['sig']}`", h["when"], h["args"], h["bound"], h["on_error"]] for h in sem["hooks"]]
    out = ["## Hooks", "", sem["hooks_intro"], "",
           _table(["Hook", "Called", "Arguments", "Bound", "If it raises"], rows), ""]
    out += ["- " + r for r in sem["hook_rules"]] + [""]
    out += ["### params", "", "`game_start` always receives a table, never `nil`:", "",
            _table(["Field", "Type", "Meaning"], [[f"`{p['field']}`" if p["field"] != "other fields" else p["field"],
                                                   p["type"], p["meaning"]] for p in sem["params"]]), ""]
    out += ["### Timing", ""] + ["- " + t for t in sem["timing"]] + [""]
    return out


def _global_full(name, g):
    out = ["## " + name, ""]
    if g.get("intro"):
        out += [g["intro"], ""]
    out += [_table(["Call", "Returns", "Bad argument", "Failure", "Notes"],
                   [[f"`{c['sig']}`", c["ret"], c["bad"], c["fail"], c["notes"]] for c in g["calls"]]), ""]
    if g.get("constants"):
        out += [_table(["Constant", "Value", "Meaning"],
                       [[f"`{c['name']}`", c["value"], c["meaning"]] for c in g["constants"]]), ""]
    for block in g.get("after", []):
        out += [block, ""]
    return out


def render_api(sem, vals):
    names = list(sem["globals"])
    out = [HEADER, "# Lua API reference", "",
           "Every global, function, method, constant and hook the Pika Engine exposes to a game pack, "
           "with its behaviour on bad input and on failure. **A name that is not on this page does not "
           "exist on the robot.** Machine-readable sources: `contract/api.json` (names, generated from the "
           "firmware), `contract/semantics.json` (behaviour), `contract/constraints.json` (numbers). "
           "Firmware surprises and PC-vs-robot differences: [Known issues](known-issues.md). "
           "The manifest: [manifest.json](manifest.md).", "",
           "**Contents:** [Conventions](#conventions) · [Hooks](#hooks) · "
           + " · ".join(f"[{n}](#{n.lower()})" for n in names)
           + " · [Sandbox](#sandbox) · [Limits](#limits)", "",
           "## Conventions", ""]
    out += ["- " + c for c in sem["conventions"]] + [""]
    out += _hooks_full(sem)
    for n in names:
        out += _global_full(n, sem["globals"][n])
    out += ["## Sandbox", ""] + ["- " + s for s in sem["sandbox"]] + [""]
    out += ["### Calls that do not exist", "", "Names from older documents and other engines. None of them exists on the robot.", "",
            _table(["Name", "Use instead"], [[f"`{x['name']}` <!-- not-an-api -->", x["instead"]] for x in sem["not_exist"]]), ""]
    out += _limits(sem)
    return _finish(out, vals, API_MD)


def _limits(sem):
    return ["## Limits", "", "Every value is generated from `contract/constraints.json` (key column).", "",
            _table(["Limit", "Value", "Past it", "Key"],
                   [[l["label"], l["value"], l["past"], "`" + l["keys"] + "`"] for l in sem["limits"]]), ""]


def render_known_issues(sem, vals):
    out = [HEADER, "# Known issues", "", sem["known_issues_intro"], ""]
    for k in sem["known_issues"]:
        out += [f'<a id="{k["id"].lower()}"></a>', f"## {k['id']}: {k['title']}", "",
                f"- **Behaviour:** {k['behaviour']}", f"- **Do:** {k['workaround']}",
                f"- **Status:** {k['status']}", "- **Source:** " + ", ".join(f"`{s}`" for s in k["src"]), ""]
    out += ['<a id="pc-vs-robot"></a>', "## PC vs robot", "", sem["pc_vs_robot_intro"], "",
            _table(["ID", "Topic", "Robot", "PC tools", "Do"],
                   [[p["id"], p["topic"], p["robot"], p["pc"], p["do"]] for p in sem["pc_vs_robot"]]), ""]
    return _finish(out, vals, KI_MD)


def render_skill_api(sem, vals):
    names = list(sem["globals"])
    out = [HEADER, "# API contract", "",
           "> **Closed list.** Every callable name is below; anything else does not exist on the robot. "
           "Generated from `contract/semantics.json`; full reference with the same content: "
           "[../docs/reference/api.md](../docs/reference/api.md). Limits: [constraints.md](constraints.md).", "",
           "Globals: " + " ".join(f"`{n}`" for n in names) + ".", "",
           "## Conventions", ""]
    out += ["- " + c for c in sem["conventions"]] + [""]
    out += ["## Hooks", "", sem["hooks_intro"], "",
            _table(["Hook", "Bound", "If it raises"], [[f"`{h['sig']}`", h["bound"], h["on_error"]] for h in sem["hooks"]]), ""]
    out += ["- " + r for r in sem["hook_rules"]] + ["- " + t for t in sem["timing"]] + [""]
    out += ["`params`: " + "; ".join(f"`{p['field']}` ({p['type']}): {p['meaning']}" for p in sem["params"]), ""]
    for n in names:
        g = sem["globals"][n]
        out += ["## " + n, ""]
        if g.get("intro"):
            out += [g["intro"], ""]
        out += [_table(["Call", "Returns", "On failure", "Notes"],
                       [[f"`{c['sig']}`", c["ret"], _failure(c), c.get("brief", _brief(c["notes"]))]
                        for c in g["calls"]]), ""]
        if g.get("constants"):
            out += ["Constants: " + ", ".join(f"`{c['name']}`" for c in g["constants"])
                    + ". Compare with the constants, never with numbers.", ""]
        for i in g.get("skill_after", []):
            out += [g["after"][i], ""]
    out += ["## Sandbox", ""] + ["- " + s for s in sem["sandbox"]] + [""]
    out += ["## Does NOT exist (commonly invented)", "",
            _table(["Invented", "Use instead"], [[f"`{x['name']}` <!-- not-an-api -->", x["instead"]] for x in sem["not_exist"]]), "",
            "If a game needs something missing, tell the user and propose an alternative; never invent a call.", ""]
    return _finish(out, vals, SKILL_API)


def render_skill_limits(sem, vals):
    out = [HEADER, "# Hard constraints", "",
           "> Breaking a limit is not \"slow\": the call fails, the hook is killed or the pack is rejected. "
           "Values come from `contract/constraints.json`, generated from the firmware.", ""]
    out += _limits(sem)[2:]
    out += ["## Facts that shape designs", ""] + ["- " + f for f in sem["facts"]] + [""]
    out += ["## Known issues", "", "Work around each; details in "
            "[../docs/reference/known-issues.md](../docs/reference/known-issues.md).", ""]
    out += [f"- **{k['id']}** {k['title']}. *Do:* {k['workaround']}" for k in sem["known_issues"]] + [""]
    out += ["## PC vs robot", "", "Passing `tools/smoke.py` or Pika Studio does not prove these:", "",
            _table(["ID", "Topic", "Do"], [[p["id"], p["topic"], p["do"]] for p in sem["pc_vs_robot"]]), ""]
    return _finish(out, vals, SKILL_LIM)


def _finish(lines, vals, page):
    text = "\n".join(lines).rstrip("\n") + "\n"
    text = re.sub(r"\n{3,}", "\n\n", text)
    return _links(_fill(text, vals), page)


def render_pages(vals):
    """contract/pages/<name>.md -> docs/reference/<name>.md, with {{key}} filled.
    Links in a page template are written relative to its output location."""
    out = {}
    for name in sorted(os.listdir(PAGES_DIR)):
        if name.endswith(".md"):
            with open(os.path.join(PAGES_DIR, name), encoding="utf-8") as f:
                text = f.read()
            page = "docs/reference/" + name
            out[page] = _links(_fill(HEADER + "\n" + text, vals), page, page_anchors_to_api=False)
    return out


def render_all(sem, api, constraints):
    validate(sem, api)
    vals = _values(constraints)
    out = {API_MD: render_api(sem, vals), KI_MD: render_known_issues(sem, vals),
           SKILL_API: render_skill_api(sem, vals), SKILL_LIM: render_skill_limits(sem, vals)}
    out.update(render_pages(vals))
    return out
